// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright OpenBMC Authors
#pragma once
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/base_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/composition_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/environmental_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/ethernet_fabric_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/fabric_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/heartbeat_event_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/job_event_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/license_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/log_service_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/network_device_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/openbmc_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/platform_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/power_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/resource_event_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/sensor_event_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/storage_device_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/task_event_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/telemetry_message_registry.hpp"
// NOLINTNEXTLINE(misc-include-cleaner)
#include "registries/update_message_registry.hpp"
