#pragma once
/****************************************************************
 *                 READ THIS WARNING FIRST
 * This is an auto-generated header which contains definitions
 * for Redfish DMTF defined schemas.
 * DO NOT modify this registry outside of running the
 * update_schemas.py script.  The definitions contained within
 * this file are owned by DMTF.  Any modifications to these files
 * should be first pushed to the relevant registry in the DMTF
 * github organization.
 ***************************************************************/
// clang-format off

namespace redfish
{
    constexpr std::array schemas {
        "LogService",
        "ManagerAccount",
        "Resource",
        "Redundancy",
        "ThermalSubsystem",
        "Task",
        "AttributeRegistry",
        "Cable",
        "Manager",
        "Memory",
        "LogEntry",
        "Chassis",
        "ComputerSystem",
        "IPAddresses",
        "PCIeFunction",
        "Thermal",
        "Bios",
        "Processor",
        "Settings",
        "redfish-payload-annotations",
        "Triggers",
        "MetricReportDefinition",
        "Drive",
        "Session",
        "odata",
        "PCIeDevice",
        "MetricDefinition",
        "TelemetryService",
        "VLanNetworkInterface",
        "Sensor",
        "EthernetInterface",
        "MessageRegistryFile",
        "Assembly",
        "TaskService",
        "AccountService",
        "EventService",
        "JsonSchemaFile",
        "ServiceRoot",
        "Role",
        "PCIeSlots",
        "ManagerNetworkProtocol",
        "MessageRegistry",
        "VirtualMediaCollection",
        "Privileges",
        "ChassisCollection",
        "ActionInfo",
        "CableCollection",
        "redfish-schema",
        "Storage",
        "StorageController",
        "SoftwareInventory",
        "EventDestination",
        "MetricReport",
        "Power",
        "UpdateService",
        "Event",
        "VirtualMedia",
        "Certificate",
        "SessionService",
        "CertificateService",
        "Message",
        "TaskCollection",
        "PhysicalContext",
        "PCIeFunctionCollection",
        "PCIeDeviceCollection",
        "EventDestinationCollection",
        "CertificateCollection",
        "StorageCollection",
        "odata-v4",
        "CertificateLocations",
        "ComputerSystemCollection",
        "DriveCollection",
        "LogServiceCollection",
        "ManagerDiagnosticData",
        "OperatingConfig",
        "ManagerAccountCollection",
        "redfish-schema-v1",
        "SoftwareInventoryCollection",
        "SensorCollection",
        "ProcessorCollection",
        "MetricDefinitionCollection",
        "redfish-error",
        "JsonSchemaFileCollection",
        "ManagerCollection",
        "OperatingConfigCollection",
        "TriggersCollection",
        "SessionCollection",
        "LogEntryCollection",
        "MetricReportCollection",
        "RoleCollection",
        "MemoryCollection",
        "MessageRegistryCollection",
        "MessageRegistryFileCollection",
        "EthernetInterfaceCollection",
        "StorageControllerCollection",
        "MetricReportDefinitionCollection",
        "VLanNetworkInterfaceCollection",
    };
}
